services:
    deploy:
      container_name: lulc-deploy
      image: lulc
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        # For Terraform
        - TF_VAR_username=${USER}
        - TF_VAR_subscriptionId=${subscriptionId}
        - TF_VAR_mailerAddress=${mailerAddress}
        - TF_VAR_mailerDomain=${mailerDomain}
        - TF_VAR_mailerFrom=${mailerFrom}
        - TF_VAR_mailerUsername=${mailerUsername}
        - TF_VAR_mailerPassword=${mailerPassword}
        - TF_VAR_mailerPort=${mailerPort}
        - ARM_SUBSCRIPTION_ID=${subscriptionId}
        - ARM_TENANT_ID=${tenantId}
        - ARM_CLIENT_ID=${servicePrincipalId}
        - ARM_CLIENT_SECRET=${servicePrincipalKey}
        - ARM_ACCESS_KEY=${storageAccessKey}
  
        # For Azure CLI
        - AZURE_TENANT_ID=${tenantId}
        - AZURE_CLIENT_ID=${servicePrincipalId}
        - AZURE_CLIENT_SECRET=${servicePrincipalKey}
  
        # For deployment
      volumes:
        - .:/opt/src
  
